// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: genome.proto

package crogers3.proto.compiled;

public final class GenomeProtos {
  private GenomeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenomeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:crogers3.Genome)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    java.util.List<crogers3.proto.compiled.GenomeProtos.Gene> 
        getGeneList();
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    crogers3.proto.compiled.GenomeProtos.Gene getGene(int index);
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    int getGeneCount();
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    java.util.List<? extends crogers3.proto.compiled.GenomeProtos.GeneOrBuilder> 
        getGeneOrBuilderList();
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    crogers3.proto.compiled.GenomeProtos.GeneOrBuilder getGeneOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code crogers3.Genome}
   */
  public  static final class Genome extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:crogers3.Genome)
      GenomeOrBuilder {
    // Use Genome.newBuilder() to construct.
    private Genome(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Genome() {
      gene_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Genome(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                gene_ = new java.util.ArrayList<crogers3.proto.compiled.GenomeProtos.Gene>();
                mutable_bitField0_ |= 0x00000001;
              }
              gene_.add(
                  input.readMessage(crogers3.proto.compiled.GenomeProtos.Gene.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          gene_ = java.util.Collections.unmodifiableList(gene_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Genome_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Genome_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              crogers3.proto.compiled.GenomeProtos.Genome.class, crogers3.proto.compiled.GenomeProtos.Genome.Builder.class);
    }

    public static final int GENE_FIELD_NUMBER = 1;
    private java.util.List<crogers3.proto.compiled.GenomeProtos.Gene> gene_;
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    public java.util.List<crogers3.proto.compiled.GenomeProtos.Gene> getGeneList() {
      return gene_;
    }
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    public java.util.List<? extends crogers3.proto.compiled.GenomeProtos.GeneOrBuilder> 
        getGeneOrBuilderList() {
      return gene_;
    }
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    public int getGeneCount() {
      return gene_.size();
    }
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    public crogers3.proto.compiled.GenomeProtos.Gene getGene(int index) {
      return gene_.get(index);
    }
    /**
     * <code>repeated .crogers3.Gene gene = 1;</code>
     */
    public crogers3.proto.compiled.GenomeProtos.GeneOrBuilder getGeneOrBuilder(
        int index) {
      return gene_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < gene_.size(); i++) {
        output.writeMessage(1, gene_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < gene_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gene_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof crogers3.proto.compiled.GenomeProtos.Genome)) {
        return super.equals(obj);
      }
      crogers3.proto.compiled.GenomeProtos.Genome other = (crogers3.proto.compiled.GenomeProtos.Genome) obj;

      boolean result = true;
      result = result && getGeneList()
          .equals(other.getGeneList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getGeneCount() > 0) {
        hash = (37 * hash) + GENE_FIELD_NUMBER;
        hash = (53 * hash) + getGeneList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static crogers3.proto.compiled.GenomeProtos.Genome parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static crogers3.proto.compiled.GenomeProtos.Genome parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(crogers3.proto.compiled.GenomeProtos.Genome prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code crogers3.Genome}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:crogers3.Genome)
        crogers3.proto.compiled.GenomeProtos.GenomeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Genome_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Genome_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                crogers3.proto.compiled.GenomeProtos.Genome.class, crogers3.proto.compiled.GenomeProtos.Genome.Builder.class);
      }

      // Construct using crogers3.proto.compiled.GenomeProtos.Genome.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGeneFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (geneBuilder_ == null) {
          gene_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          geneBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Genome_descriptor;
      }

      public crogers3.proto.compiled.GenomeProtos.Genome getDefaultInstanceForType() {
        return crogers3.proto.compiled.GenomeProtos.Genome.getDefaultInstance();
      }

      public crogers3.proto.compiled.GenomeProtos.Genome build() {
        crogers3.proto.compiled.GenomeProtos.Genome result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public crogers3.proto.compiled.GenomeProtos.Genome buildPartial() {
        crogers3.proto.compiled.GenomeProtos.Genome result = new crogers3.proto.compiled.GenomeProtos.Genome(this);
        int from_bitField0_ = bitField0_;
        if (geneBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            gene_ = java.util.Collections.unmodifiableList(gene_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gene_ = gene_;
        } else {
          result.gene_ = geneBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof crogers3.proto.compiled.GenomeProtos.Genome) {
          return mergeFrom((crogers3.proto.compiled.GenomeProtos.Genome)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(crogers3.proto.compiled.GenomeProtos.Genome other) {
        if (other == crogers3.proto.compiled.GenomeProtos.Genome.getDefaultInstance()) return this;
        if (geneBuilder_ == null) {
          if (!other.gene_.isEmpty()) {
            if (gene_.isEmpty()) {
              gene_ = other.gene_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGeneIsMutable();
              gene_.addAll(other.gene_);
            }
            onChanged();
          }
        } else {
          if (!other.gene_.isEmpty()) {
            if (geneBuilder_.isEmpty()) {
              geneBuilder_.dispose();
              geneBuilder_ = null;
              gene_ = other.gene_;
              bitField0_ = (bitField0_ & ~0x00000001);
              geneBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGeneFieldBuilder() : null;
            } else {
              geneBuilder_.addAllMessages(other.gene_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        crogers3.proto.compiled.GenomeProtos.Genome parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (crogers3.proto.compiled.GenomeProtos.Genome) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<crogers3.proto.compiled.GenomeProtos.Gene> gene_ =
        java.util.Collections.emptyList();
      private void ensureGeneIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          gene_ = new java.util.ArrayList<crogers3.proto.compiled.GenomeProtos.Gene>(gene_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          crogers3.proto.compiled.GenomeProtos.Gene, crogers3.proto.compiled.GenomeProtos.Gene.Builder, crogers3.proto.compiled.GenomeProtos.GeneOrBuilder> geneBuilder_;

      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public java.util.List<crogers3.proto.compiled.GenomeProtos.Gene> getGeneList() {
        if (geneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gene_);
        } else {
          return geneBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public int getGeneCount() {
        if (geneBuilder_ == null) {
          return gene_.size();
        } else {
          return geneBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public crogers3.proto.compiled.GenomeProtos.Gene getGene(int index) {
        if (geneBuilder_ == null) {
          return gene_.get(index);
        } else {
          return geneBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder setGene(
          int index, crogers3.proto.compiled.GenomeProtos.Gene value) {
        if (geneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGeneIsMutable();
          gene_.set(index, value);
          onChanged();
        } else {
          geneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder setGene(
          int index, crogers3.proto.compiled.GenomeProtos.Gene.Builder builderForValue) {
        if (geneBuilder_ == null) {
          ensureGeneIsMutable();
          gene_.set(index, builderForValue.build());
          onChanged();
        } else {
          geneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder addGene(crogers3.proto.compiled.GenomeProtos.Gene value) {
        if (geneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGeneIsMutable();
          gene_.add(value);
          onChanged();
        } else {
          geneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder addGene(
          int index, crogers3.proto.compiled.GenomeProtos.Gene value) {
        if (geneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGeneIsMutable();
          gene_.add(index, value);
          onChanged();
        } else {
          geneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder addGene(
          crogers3.proto.compiled.GenomeProtos.Gene.Builder builderForValue) {
        if (geneBuilder_ == null) {
          ensureGeneIsMutable();
          gene_.add(builderForValue.build());
          onChanged();
        } else {
          geneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder addGene(
          int index, crogers3.proto.compiled.GenomeProtos.Gene.Builder builderForValue) {
        if (geneBuilder_ == null) {
          ensureGeneIsMutable();
          gene_.add(index, builderForValue.build());
          onChanged();
        } else {
          geneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder addAllGene(
          java.lang.Iterable<? extends crogers3.proto.compiled.GenomeProtos.Gene> values) {
        if (geneBuilder_ == null) {
          ensureGeneIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gene_);
          onChanged();
        } else {
          geneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder clearGene() {
        if (geneBuilder_ == null) {
          gene_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          geneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public Builder removeGene(int index) {
        if (geneBuilder_ == null) {
          ensureGeneIsMutable();
          gene_.remove(index);
          onChanged();
        } else {
          geneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public crogers3.proto.compiled.GenomeProtos.Gene.Builder getGeneBuilder(
          int index) {
        return getGeneFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public crogers3.proto.compiled.GenomeProtos.GeneOrBuilder getGeneOrBuilder(
          int index) {
        if (geneBuilder_ == null) {
          return gene_.get(index);  } else {
          return geneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public java.util.List<? extends crogers3.proto.compiled.GenomeProtos.GeneOrBuilder> 
           getGeneOrBuilderList() {
        if (geneBuilder_ != null) {
          return geneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gene_);
        }
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public crogers3.proto.compiled.GenomeProtos.Gene.Builder addGeneBuilder() {
        return getGeneFieldBuilder().addBuilder(
            crogers3.proto.compiled.GenomeProtos.Gene.getDefaultInstance());
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public crogers3.proto.compiled.GenomeProtos.Gene.Builder addGeneBuilder(
          int index) {
        return getGeneFieldBuilder().addBuilder(
            index, crogers3.proto.compiled.GenomeProtos.Gene.getDefaultInstance());
      }
      /**
       * <code>repeated .crogers3.Gene gene = 1;</code>
       */
      public java.util.List<crogers3.proto.compiled.GenomeProtos.Gene.Builder> 
           getGeneBuilderList() {
        return getGeneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          crogers3.proto.compiled.GenomeProtos.Gene, crogers3.proto.compiled.GenomeProtos.Gene.Builder, crogers3.proto.compiled.GenomeProtos.GeneOrBuilder> 
          getGeneFieldBuilder() {
        if (geneBuilder_ == null) {
          geneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              crogers3.proto.compiled.GenomeProtos.Gene, crogers3.proto.compiled.GenomeProtos.Gene.Builder, crogers3.proto.compiled.GenomeProtos.GeneOrBuilder>(
                  gene_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          gene_ = null;
        }
        return geneBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:crogers3.Genome)
    }

    // @@protoc_insertion_point(class_scope:crogers3.Genome)
    private static final crogers3.proto.compiled.GenomeProtos.Genome DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new crogers3.proto.compiled.GenomeProtos.Genome();
    }

    public static crogers3.proto.compiled.GenomeProtos.Genome getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Genome>
        PARSER = new com.google.protobuf.AbstractParser<Genome>() {
      public Genome parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Genome(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Genome> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Genome> getParserForType() {
      return PARSER;
    }

    public crogers3.proto.compiled.GenomeProtos.Genome getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GeneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:crogers3.Gene)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 inNode = 1;</code>
     */
    boolean hasInNode();
    /**
     * <code>optional int32 inNode = 1;</code>
     */
    int getInNode();

    /**
     * <code>optional int32 outNode = 2;</code>
     */
    boolean hasOutNode();
    /**
     * <code>optional int32 outNode = 2;</code>
     */
    int getOutNode();

    /**
     * <code>optional double weight = 3;</code>
     */
    boolean hasWeight();
    /**
     * <code>optional double weight = 3;</code>
     */
    double getWeight();

    /**
     * <code>optional bool enabled = 4;</code>
     */
    boolean hasEnabled();
    /**
     * <code>optional bool enabled = 4;</code>
     */
    boolean getEnabled();

    /**
     * <code>optional int32 innovation_number = 5;</code>
     */
    boolean hasInnovationNumber();
    /**
     * <code>optional int32 innovation_number = 5;</code>
     */
    int getInnovationNumber();
  }
  /**
   * Protobuf type {@code crogers3.Gene}
   */
  public  static final class Gene extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:crogers3.Gene)
      GeneOrBuilder {
    // Use Gene.newBuilder() to construct.
    private Gene(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Gene() {
      inNode_ = 0;
      outNode_ = 0;
      weight_ = 0D;
      enabled_ = false;
      innovationNumber_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Gene(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              inNode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              outNode_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              weight_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              enabled_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              innovationNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Gene_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Gene_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              crogers3.proto.compiled.GenomeProtos.Gene.class, crogers3.proto.compiled.GenomeProtos.Gene.Builder.class);
    }

    private int bitField0_;
    public static final int INNODE_FIELD_NUMBER = 1;
    private int inNode_;
    /**
     * <code>optional int32 inNode = 1;</code>
     */
    public boolean hasInNode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 inNode = 1;</code>
     */
    public int getInNode() {
      return inNode_;
    }

    public static final int OUTNODE_FIELD_NUMBER = 2;
    private int outNode_;
    /**
     * <code>optional int32 outNode = 2;</code>
     */
    public boolean hasOutNode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 outNode = 2;</code>
     */
    public int getOutNode() {
      return outNode_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 3;
    private double weight_;
    /**
     * <code>optional double weight = 3;</code>
     */
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double weight = 3;</code>
     */
    public double getWeight() {
      return weight_;
    }

    public static final int ENABLED_FIELD_NUMBER = 4;
    private boolean enabled_;
    /**
     * <code>optional bool enabled = 4;</code>
     */
    public boolean hasEnabled() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool enabled = 4;</code>
     */
    public boolean getEnabled() {
      return enabled_;
    }

    public static final int INNOVATION_NUMBER_FIELD_NUMBER = 5;
    private int innovationNumber_;
    /**
     * <code>optional int32 innovation_number = 5;</code>
     */
    public boolean hasInnovationNumber() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 innovation_number = 5;</code>
     */
    public int getInnovationNumber() {
      return innovationNumber_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, inNode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, outNode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, weight_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, enabled_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, innovationNumber_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, inNode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, outNode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, weight_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, enabled_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, innovationNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof crogers3.proto.compiled.GenomeProtos.Gene)) {
        return super.equals(obj);
      }
      crogers3.proto.compiled.GenomeProtos.Gene other = (crogers3.proto.compiled.GenomeProtos.Gene) obj;

      boolean result = true;
      result = result && (hasInNode() == other.hasInNode());
      if (hasInNode()) {
        result = result && (getInNode()
            == other.getInNode());
      }
      result = result && (hasOutNode() == other.hasOutNode());
      if (hasOutNode()) {
        result = result && (getOutNode()
            == other.getOutNode());
      }
      result = result && (hasWeight() == other.hasWeight());
      if (hasWeight()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getWeight())
            == java.lang.Double.doubleToLongBits(
                other.getWeight()));
      }
      result = result && (hasEnabled() == other.hasEnabled());
      if (hasEnabled()) {
        result = result && (getEnabled()
            == other.getEnabled());
      }
      result = result && (hasInnovationNumber() == other.hasInnovationNumber());
      if (hasInnovationNumber()) {
        result = result && (getInnovationNumber()
            == other.getInnovationNumber());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasInNode()) {
        hash = (37 * hash) + INNODE_FIELD_NUMBER;
        hash = (53 * hash) + getInNode();
      }
      if (hasOutNode()) {
        hash = (37 * hash) + OUTNODE_FIELD_NUMBER;
        hash = (53 * hash) + getOutNode();
      }
      if (hasWeight()) {
        hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getWeight()));
      }
      if (hasEnabled()) {
        hash = (37 * hash) + ENABLED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getEnabled());
      }
      if (hasInnovationNumber()) {
        hash = (37 * hash) + INNOVATION_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getInnovationNumber();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static crogers3.proto.compiled.GenomeProtos.Gene parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static crogers3.proto.compiled.GenomeProtos.Gene parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(crogers3.proto.compiled.GenomeProtos.Gene prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code crogers3.Gene}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:crogers3.Gene)
        crogers3.proto.compiled.GenomeProtos.GeneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Gene_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Gene_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                crogers3.proto.compiled.GenomeProtos.Gene.class, crogers3.proto.compiled.GenomeProtos.Gene.Builder.class);
      }

      // Construct using crogers3.proto.compiled.GenomeProtos.Gene.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        inNode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        outNode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        weight_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        enabled_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        innovationNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return crogers3.proto.compiled.GenomeProtos.internal_static_crogers3_Gene_descriptor;
      }

      public crogers3.proto.compiled.GenomeProtos.Gene getDefaultInstanceForType() {
        return crogers3.proto.compiled.GenomeProtos.Gene.getDefaultInstance();
      }

      public crogers3.proto.compiled.GenomeProtos.Gene build() {
        crogers3.proto.compiled.GenomeProtos.Gene result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public crogers3.proto.compiled.GenomeProtos.Gene buildPartial() {
        crogers3.proto.compiled.GenomeProtos.Gene result = new crogers3.proto.compiled.GenomeProtos.Gene(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.inNode_ = inNode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.outNode_ = outNode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.weight_ = weight_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.enabled_ = enabled_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.innovationNumber_ = innovationNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof crogers3.proto.compiled.GenomeProtos.Gene) {
          return mergeFrom((crogers3.proto.compiled.GenomeProtos.Gene)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(crogers3.proto.compiled.GenomeProtos.Gene other) {
        if (other == crogers3.proto.compiled.GenomeProtos.Gene.getDefaultInstance()) return this;
        if (other.hasInNode()) {
          setInNode(other.getInNode());
        }
        if (other.hasOutNode()) {
          setOutNode(other.getOutNode());
        }
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        if (other.hasEnabled()) {
          setEnabled(other.getEnabled());
        }
        if (other.hasInnovationNumber()) {
          setInnovationNumber(other.getInnovationNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        crogers3.proto.compiled.GenomeProtos.Gene parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (crogers3.proto.compiled.GenomeProtos.Gene) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int inNode_ ;
      /**
       * <code>optional int32 inNode = 1;</code>
       */
      public boolean hasInNode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 inNode = 1;</code>
       */
      public int getInNode() {
        return inNode_;
      }
      /**
       * <code>optional int32 inNode = 1;</code>
       */
      public Builder setInNode(int value) {
        bitField0_ |= 0x00000001;
        inNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 inNode = 1;</code>
       */
      public Builder clearInNode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        inNode_ = 0;
        onChanged();
        return this;
      }

      private int outNode_ ;
      /**
       * <code>optional int32 outNode = 2;</code>
       */
      public boolean hasOutNode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 outNode = 2;</code>
       */
      public int getOutNode() {
        return outNode_;
      }
      /**
       * <code>optional int32 outNode = 2;</code>
       */
      public Builder setOutNode(int value) {
        bitField0_ |= 0x00000002;
        outNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 outNode = 2;</code>
       */
      public Builder clearOutNode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        outNode_ = 0;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>optional double weight = 3;</code>
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double weight = 3;</code>
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>optional double weight = 3;</code>
       */
      public Builder setWeight(double value) {
        bitField0_ |= 0x00000004;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double weight = 3;</code>
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        weight_ = 0D;
        onChanged();
        return this;
      }

      private boolean enabled_ ;
      /**
       * <code>optional bool enabled = 4;</code>
       */
      public boolean hasEnabled() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool enabled = 4;</code>
       */
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>optional bool enabled = 4;</code>
       */
      public Builder setEnabled(boolean value) {
        bitField0_ |= 0x00000008;
        enabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool enabled = 4;</code>
       */
      public Builder clearEnabled() {
        bitField0_ = (bitField0_ & ~0x00000008);
        enabled_ = false;
        onChanged();
        return this;
      }

      private int innovationNumber_ ;
      /**
       * <code>optional int32 innovation_number = 5;</code>
       */
      public boolean hasInnovationNumber() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 innovation_number = 5;</code>
       */
      public int getInnovationNumber() {
        return innovationNumber_;
      }
      /**
       * <code>optional int32 innovation_number = 5;</code>
       */
      public Builder setInnovationNumber(int value) {
        bitField0_ |= 0x00000010;
        innovationNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 innovation_number = 5;</code>
       */
      public Builder clearInnovationNumber() {
        bitField0_ = (bitField0_ & ~0x00000010);
        innovationNumber_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:crogers3.Gene)
    }

    // @@protoc_insertion_point(class_scope:crogers3.Gene)
    private static final crogers3.proto.compiled.GenomeProtos.Gene DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new crogers3.proto.compiled.GenomeProtos.Gene();
    }

    public static crogers3.proto.compiled.GenomeProtos.Gene getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Gene>
        PARSER = new com.google.protobuf.AbstractParser<Gene>() {
      public Gene parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Gene(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Gene> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Gene> getParserForType() {
      return PARSER;
    }

    public crogers3.proto.compiled.GenomeProtos.Gene getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crogers3_Genome_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crogers3_Genome_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crogers3_Gene_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crogers3_Gene_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014genome.proto\022\010crogers3\"&\n\006Genome\022\034\n\004ge" +
      "ne\030\001 \003(\0132\016.crogers3.Gene\"c\n\004Gene\022\016\n\006inNo" +
      "de\030\001 \001(\005\022\017\n\007outNode\030\002 \001(\005\022\016\n\006weight\030\003 \001(" +
      "\001\022\017\n\007enabled\030\004 \001(\010\022\031\n\021innovation_number\030" +
      "\005 \001(\005B\'\n\027crogers3.proto.compiledB\014Genome" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_crogers3_Genome_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crogers3_Genome_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crogers3_Genome_descriptor,
        new java.lang.String[] { "Gene", });
    internal_static_crogers3_Gene_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_crogers3_Gene_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crogers3_Gene_descriptor,
        new java.lang.String[] { "InNode", "OutNode", "Weight", "Enabled", "InnovationNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
